version: '3.9'

services:
  earthquake-webhost:
    container_name: earthquake-webhost
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 80
    volumes:
      - ./data:/var/www/html
      - ./data/public:/usr/share/nginx/html
    environment:
      TZ: America/Vancouver
